// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250517132527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBan"));

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaBan");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("Backend.Models.BoPhan", b =>
                {
                    b.Property<int>("MaBoPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBoPhan"));

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaBoPhan");

                    b.ToTable("BoPhan");

                    b.HasData(
                        new
                        {
                            MaBoPhan = 1,
                            TenBoPhan = "Ban Quản Lý"
                        });
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.HasKey("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioVao")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("Backend.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.Property<int>("MaDatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDatBan"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.Property<int>("MaKH")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("DatBan");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDonHang");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NgayDat");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("GiaoDichKho");
                });

            modelBuilder.Entity("Backend.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.Kho", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuongHienTai")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoLuongToiThieu")
                        .HasColumnType("numeric");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKM"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("numeric");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaKM");

                    b.HasIndex("NgayBatDau", "NgayKetThuc");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("numeric");

                    b.HasKey("MaDonHang", "MaKhuyenMai");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("KhuyenMai_DonHang");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLichLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLichLamViec"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaCa")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaLichLamViec");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien", "NgayLamViec", "MaCa")
                        .IsUnique();

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("Backend.Models.LoaiMon", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiMon");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaBoPhan")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaBoPhan");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            ChucVu = "QuanLy",
                            DiaChi = "Admin Address",
                            Email = "admin@gmail.com",
                            HoTen = "Admin",
                            MaBoPhan = 1,
                            MatKhau = "$2a$11$AHzAlAtAtx.m0g8q0x5nj.LB42KsSQx3hlzv7yE3UQGnn6oNhxIqm",
                            SDT = "0123456789",
                            TrangThai = "Đang làm việc"
                        });
                });

            modelBuilder.Entity("Backend.Models.ThucDon", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMon"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KhuyenMaiMaKM")
                        .HasColumnType("integer");

                    b.Property<int>("MaLoai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaMon");

                    b.HasIndex("KhuyenMaiMaKM");

                    b.HasIndex("MaLoai");

                    b.HasIndex("TenMon");

                    b.ToTable("ThucDon");
                });

            modelBuilder.Entity("Backend.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MoTa = "Quản lý hệ thống",
                            TenVaiTro = "QuanLy"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MoTa = "Nhân viên",
                            TenVaiTro = "NhanVien"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MoTa = "Khách hàng",
                            TenVaiTro = "KhachHang"
                        });
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany("CaLamViec")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ThucDon", "ThucDon")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("ThucDon");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.HasOne("Backend.Models.Ban", "Ban")
                        .WithMany("DatBan")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany("DonHang")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang");

                    b.HasOne("Backend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_DonHang", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.HasOne("Backend.Models.CaLamViec", "CaLamViec")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.HasOne("Backend.Models.BoPhan", "BoPhan")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaBoPhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("Backend.Models.ThucDon", b =>
                {
                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiMaKM");

                    b.HasOne("Backend.Models.LoaiMon", "LoaiMon")
                        .WithMany("ThucDons")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("LoaiMon");
                });

            modelBuilder.Entity("Backend.Models.Ban", b =>
                {
                    b.Navigation("DatBan");
                });

            modelBuilder.Entity("Backend.Models.BoPhan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });

            modelBuilder.Entity("Backend.Models.KhachHang", b =>
                {
                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("Backend.Models.LoaiMon", b =>
                {
                    b.Navigation("ThucDons");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.Navigation("CaLamViec");

                    b.Navigation("ChamCong");
                });

            modelBuilder.Entity("Backend.Models.ThucDon", b =>
                {
                    b.Navigation("ChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
