// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250602170906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBan"));

                    b.Property<int>("SoLuongDatCho")
                        .HasColumnType("integer");

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaBan");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("Backend.Models.BoPhan", b =>
                {
                    b.Property<int>("MaBoPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBoPhan"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaBoPhan");

                    b.ToTable("BoPhan");
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.HasKey("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioVao")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("Backend.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.Property<int>("MaDatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDatBan"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.Property<int>("MaKH")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("DatBan");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NgayDat");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("GiaoDichKho");
                });

            modelBuilder.Entity("Backend.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Backend.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.Kho", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaNCC")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuongHienTai")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoLuongToiThieu")
                        .HasColumnType("numeric");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaNCC");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<string>("DieuKien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("numeric");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("NgayBatDau", "NgayKetThuc");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_MonAn", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.HasKey("MaKhuyenMai", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("KhuyenMai_MonAn");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLichLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLichLamViec"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaCa")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaLichLamViec");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("Backend.Models.LichSuKhuyenMai", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("numeric");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("LichSuKhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.LoaiMon", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiMon");
                });

            modelBuilder.Entity("Backend.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMon"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KhuyenMaiMaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<int?>("MaKM")
                        .HasColumnType("integer");

                    b.Property<int>("MaLoai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaMon");

                    b.HasIndex("KhuyenMaiMaKhuyenMai");

                    b.HasIndex("MaLoai");

                    b.HasIndex("TenMon");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("Backend.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<int>("MaNL")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNL");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("Backend.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNV"));

                    b.Property<int>("BoPhanMaBoPhan")
                        .HasColumnType("integer");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaBoPhan")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("MaNV");

                    b.HasIndex("BoPhanMaBoPhan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Backend.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MoTa = "Quản lý hệ thống với toàn quyền truy cập",
                            TenVaiTro = "Quản lý"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MoTa = "Nhân viên với quyền truy cập hạn chế",
                            TenVaiTro = "Nhân viên"
                        });
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany("CaLamViec")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.HasOne("Backend.Models.Ban", "Ban")
                        .WithMany("DatBan")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany("DonHang")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang");

                    b.HasOne("Backend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("Backend.Models.HoaDon", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithOne("HoaDon")
                        .HasForeignKey("Backend.Models.HoaDon", "MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.Kho", b =>
                {
                    b.HasOne("Backend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("NguyenLieu")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_MonAn", b =>
                {
                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("KhuyenMai_MonAn")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.HasOne("Backend.Models.CaLamViec", "CaLamViec")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.LichSuKhuyenMai", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("LichSuKhuyenMai")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.MonAn", b =>
                {
                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiMaKhuyenMai");

                    b.HasOne("Backend.Models.LoaiMon", "LoaiMon")
                        .WithMany("MonAns")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("LoaiMon");
                });

            modelBuilder.Entity("Backend.Models.NguyenLieu", b =>
                {
                    b.HasOne("Backend.Models.MonAn", "MonAn")
                        .WithMany("NguyenLieu")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Kho", "KhoNguyenLieu")
                        .WithMany("NguyenLieu")
                        .HasForeignKey("MaNL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoNguyenLieu");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.HasOne("Backend.Models.BoPhan", "BoPhan")
                        .WithMany("NhanVien")
                        .HasForeignKey("BoPhanMaBoPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("Backend.Models.TaiKhoan", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.HasOne("Backend.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Backend.Models.Ban", b =>
                {
                    b.Navigation("DatBan");
                });

            modelBuilder.Entity("Backend.Models.BoPhan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Backend.Models.KhachHang", b =>
                {
                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("Backend.Models.Kho", b =>
                {
                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai", b =>
                {
                    b.Navigation("KhuyenMai_MonAn");

                    b.Navigation("LichSuKhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.LoaiMon", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("Backend.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHang");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("Backend.Models.NhaCungCap", b =>
                {
                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.Navigation("CaLamViec");

                    b.Navigation("ChamCong");
                });

            modelBuilder.Entity("Backend.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
