// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Ban", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("Backend.Models.CT_DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaMon")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaTaiThoiDiem")
                        .HasColumnType("numeric");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaDonHang", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("CT_DonHang");
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.HasKey("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("GioVao")
                        .HasColumnType("interval");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.Property<int>("MaDatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDatBan"));

                    b.Property<int>("MaBan")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("integer");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DatBan");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ThucDonID")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDonHang");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("ThucDonID");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("numeric");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("GiaoDichKho");
                });

            modelBuilder.Entity("Backend.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.Kho", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SoLuongHienTai")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoLuongToiThieu")
                        .HasColumnType("numeric");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("numeric");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("numeric");

                    b.HasKey("MaDonHang", "MaKhuyenMai");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("KhuyenMai_DonHang");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaCa")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ThucDon", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaMon"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("numeric");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoaiMon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("MaMon");

                    b.ToTable("ThucDon");
                });

            modelBuilder.Entity("Backend.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Backend.Models.CT_DonHang", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ThucDon", "ThucDon")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("ThucDon");
                });

            modelBuilder.Entity("Backend.Models.CaLamViec", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.ChamCong", b =>
                {
                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.DatBan", b =>
                {
                    b.HasOne("Backend.Models.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Backend.Models.DonHang", b =>
                {
                    b.HasOne("Backend.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ThucDon", "ThucDon")
                        .WithMany()
                        .HasForeignKey("ThucDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("ThucDon");
                });

            modelBuilder.Entity("Backend.Models.GiaoDichKho", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang");

                    b.HasOne("Backend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("Backend.Models.KhuyenMai_DonHang", b =>
                {
                    b.HasOne("Backend.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Backend.Models.LichLamViec", b =>
                {
                    b.HasOne("Backend.Models.CaLamViec", "CaLamViec")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Backend.Models.NhanVien", b =>
                {
                    b.HasOne("Backend.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });
#pragma warning restore 612, 618
        }
    }
}
